spring.application.name=api-peliculas

spring.datasource.url=jdbc:mysql://localhost:3306/peliculasdb
spring.datasource.username=root
spring.datasource.password=208arco4*

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==============================
# SPRING BOOT ACTUATOR
# ==============================

# Exponer los endpoints de Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus

# Mostrar detalles completos del estado de la aplicación
management.endpoint.health.show-details=always

# Nombre de la aplicación
management.info.env.enabled=true

# Información de la aplicación
info.app.name=API Películas
info.app.description=API REST de películas con integración a TVmaze
info.app.version=0.0.1